import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LeftNav from "../components/LeftNav";
import styles from "../styles/Home.module.css";
import "semantic-ui-css/semantic.min.css";
import Header from "../components/Header";
import Content from "../components/Content";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LeftNav />
      <Header />
      <Content />
    </div>
  );
};

export default Home;
